### ISSUE TITLE
Usage example in the README

### ISSUE THREAD

**Issue by rostandkenne** [shripalsoni04/nativescript-material-icons#1]
Hi,
Can someone provide an example on how to use the plugin ?

**Comment by shripalsoni04** [comment]
Hi @joeyfromnijmegen ,

I have written a [tutorial](http://shripalsoni.com/blog/material-font-icons-in-nativescript-angular-apps/) on how to use material design font icons in your nativescript angular app. Also check this [demo app](https://github.com/shripalsoni04/ns-ng-material-icons-demo).

Hope this will be useful to you.
